label: Polish
pages:
    -
        label: The Black Hack
        author: Tomasz Misterka
        version: '1.0'
    -
        label: Additional Things
        author: David Black
        version: '1.0'
        filename: additional-things.md